name: adote_um_pet
description: Adote um Pet app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.2 <3.0.0'

dependencies:
  mysql_client: ^0.0.27
  flutter_dotenv: ^5.1.0
  bcrypt: ^1.1.3
  material_design_icons_flutter: ^7.0.7296
  dropdown_button2: ^2.1.4
  cidades_estados_ibge: ^0.1.1
  infinity_page_view_astro: ^1.0.0
  mask_text_input_formatter: ^2.4.0
  shared_preferences: ^2.0.15
  image_picker: ^0.8.6+1
  motion_toast: ^2.6.5
  gallery_saver: ^2.3.2
  remove_diacritic: ^0.9.0
  flutter_chat_bubble: ^2.0.2
  socket_io_client: 1.0.0
  intl: ^0.17.0
  uuid: ^4.1.0
  flutter_local_notifications: ^16.1.0
  provider:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mobx_codegen: ^2.0.7

flutter:
  uses-material-design: true

  assets:
    - lib/resources/
    - env.env